import GeminiContractProcessor from '../components/GeminiContractProcessor';
import Navigation from '../components/Navigation';

export const metadata = {
  title: 'Gemini Contract Processor | Avalanche',
  description: 'Process and fix contracts generated by Gemini AI',
};

export default function GeminiProcessorPage() {
  return (
    <div className="flex flex-col min-h-screen">
      <Navigation />
      <main className="flex-grow container mx-auto p-4">
        <GeminiContractProcessor />
      </main>
      <footer className="text-center p-4 text-sm text-gray-600">
        © {new Date().getFullYear()} Avalanche Smart Contract Platform
      </footer>
    </div>
  );
}